# Label configuration for GitHub
# This file defines all labels that should exist in the repository
# Used by the label-sync workflow to maintain consistent labeling

# Priority Labels
- name: "priority: critical"
  color: "d73a4a"
  description: "Critical priority"

- name: "priority: high"
  color: "ff6b6b"
  description: "High priority"

- name: "priority: medium"
  color: "ffa500"
  description: "Medium priority"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority"

# Type Labels
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "security"
  color: "d93f0b"
  description: "Security related"

- name: "task"
  color: "d4c5f9"
  description: "General task or work item"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

# Status Labels
- name: "triage"
  color: "fbca04"
  description: "Needs triage"

- name: "in-progress"
  color: "0052cc"
  description: "Work in progress"

- name: "blocked"
  color: "b60205"
  description: "Blocked by dependency"

- name: "needs-review"
  color: "6f42c1"
  description: "Ready for review"

- name: "approved"
  color: "0e8a16"
  description: "Approved and ready to merge"

# Category Labels
- name: "category: github-actions"
  color: "2088ff"
  description: "Related to GitHub Actions workflows"

- name: "category: configuration"
  color: "e99695"
  description: "Configuration files or settings"

- name: "category: dependencies"
  color: "0366d6"
  description: "Dependency updates or issues"

- name: "category: automated"
  color: "bfd4f2"
  description: "Automated processes or bots"

# Additional Labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "stale"
  color: "ededed"
  description: "Marked as stale due to inactivity"

- name: "pinned"
  color: "0e8a16"
  description: "Pinned and exempt from stale management"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency"

- name: "automated"
  color: "bfd4f2"
  description: "Automated changes from bots"
