# Label Sync Configuration
# This file defines the standard labels for the organization
# Use with github-label-sync or similar tools to maintain consistent labeling

# Priority Labels
- name: 'priority: critical'
  color: d73a4a
  description: Critical priority - immediate attention required

- name: 'priority: high'
  color: ff6b6b
  description: High priority - should be addressed soon

- name: 'priority: medium'
  color: ffa500
  description: Medium priority - normal queue

- name: 'priority: low'
  color: 0e8a16
  description: Low priority - can be scheduled later

# Type Labels
- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: feature-request
  color: 84b6eb
  description: Feature request from users or stakeholders

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: best-practices
  color: 0e8a16
  description: Best practices review or improvement

- name: security
  color: d93f0b
  description: Security vulnerability or security-related issue

- name: task
  color: 7057ff
  description: General task or work item

- name: question
  color: d876e3
  description: Further information is requested

# Status Labels
- name: triage
  color: fbca04
  description: Needs triage and initial assessment

- name: needs-triage
  color: fbca04
  description: Needs triage and initial review

- name: in-progress
  color: 0052cc
  description: Work is currently in progress

- name: blocked
  color: b60205
  description: Blocked by another issue or external dependency

- name: needs-review
  color: 6f42c1
  description: Waiting for code review

- name: review
  color: 6f42c1
  description: Review requested or in progress

- name: approved
  color: 0e8a16
  description: Approved and ready to merge

# Category Labels
- name: github-actions
  color: '000000'
  description: Related to GitHub Actions workflows

- name: configuration
  color: bfdadc
  description: Configuration changes

- name: devops
  color: 1d76db
  description: DevOps or CI/CD operations

- name: infrastructure
  color: 0e8a16
  description: Infrastructure or platform changes

- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file

- name: automated
  color: ededed
  description: Automated changes (e.g., Dependabot, bots)

# Additional Type Labels
- name: breaking-change
  color: d93f0b
  description: Breaking change that requires migration

- name: performance
  color: f9d0c4
  description: Performance improvements

- name: tech-debt
  color: f9d0c4
  description: Technical debt cleanup or remediation

- name: refactoring
  color: fbca04
  description: Code refactoring without functional changes

- name: testing
  color: c5def5
  description: Related to testing

- name: accessibility
  color: f9c513
  description: Accessibility improvements

- name: walkthrough
  color: c2e0c6
  description: Walkthrough request or guided setup

# Status Labels (continued)
- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: help-wanted
  color: '008672'
  description: Extra attention is needed - looking for contributors

- name: good-first-issue
  color: 7057ff
  description: Good for newcomers

- name: stale
  color: eeeeee
  description: Stale issue or PR - no recent activity

# Community Labels
- name: community
  color: bfd4f2
  description: Community engagement or health

- name: health-check
  color: cfd3d7
  description: Community or repository health check

# Area Labels
- name: 'area: ci-cd'
  color: 1d76db
  description: Continuous Integration / Continuous Deployment

- name: 'area: api'
  color: '5319e7'
  description: API-related changes

- name: 'area: ui'
  color: c2e0c6
  description: User interface changes

- name: 'area: infrastructure'
  color: 0e8a16
  description: Infrastructure and deployment
