# Proactive Maintenance Configuration
#
# Configures ML-based maintenance scheduling for optimal timing:
# - Dependency updates: Automated package/library updates
# - Cleanup tasks: Stale branch removal, artifact cleanup
# - Optimization: Performance tuning, cache management

maintenance:
  # Enable proactive maintenance
  enabled: true

  # Timing prediction method
  # Options: "ml" (machine learning), "fixed" (predefined schedule)
  timing_predictor: ml

  # Preferred maintenance windows
  preferred_hours:
    - 2 # 2 AM
    - 3 # 3 AM
    - 4 # 4 AM

  preferred_days:
    - 6 # Saturday
    - 0 # Sunday (0=Monday, 6=Sunday)

  # Dates to avoid (holidays, releases, etc.)
  # Format: YYYY-MM-DD
  avoid_dates:
    - "2026-12-25" # Christmas
    - "2026-01-01" # New Year
      # Add organization-specific dates

  # Dependency Updates
  dependency_updates:
    enabled: true
    frequency: weekly # Options: daily, weekly, monthly
    auto_merge: false # Auto-merge after testing
    auto_merge_minor: true # Auto-merge minor/patch updates only
    test_before_merge: true
    rollback_on_failure: true

    # Sources to monitor
    sources:
      - dependabot
      - renovate

    # Update strategies
    strategies:
      security: immediate # Security updates ASAP
      major: manual # Major versions need review
      minor: auto # Auto-merge minor versions
      patch: auto # Auto-merge patches

  # Cleanup Tasks
  cleanup:
    enabled: true
    frequency: daily # How often to check for cleanup

    # Stale branch cleanup
    stale_branches:
      enabled: true
      days: 30 # Delete branches older than 30 days
      exclude_patterns:
        - main
        - master
        - develop
        - release/*
        - hotfix/*
      require_pr_merged: true # Only delete if PR was merged

    # Old artifacts cleanup
    old_artifacts:
      enabled: true
      days: 90 # Delete artifacts older than 90 days
      keep_latest: 5 # Always keep N latest artifacts

    # Workflow run cleanup
    old_workflow_runs:
      enabled: true
      days: 90
      keep_failed: true # Keep failed runs for debugging

    # Cache cleanup
    cache_cleanup:
      enabled: true
      max_size_gb: 10 # Maximum cache size
      strategy: lru # Least recently used

  # Optimization Tasks
  optimization:
    enabled: true
    frequency: monthly

    # Database optimization
    database:
      enabled: false
      tasks:
        - index_rebuild
        - vacuum
        - analyze

    # Cache optimization
    cache:
      enabled: true
      tasks:
        - warm_cache
        - prune_stale

    # Performance tuning
    performance:
      enabled: true
      tasks:
        - update_search_index
        - optimize_images

  # Notification settings
  notifications:
    enabled: true

    # Notify before maintenance window
    notify_before_minutes: 30

    # Notify after completion
    notify_after: true

    # Notification channels
    channels:
      slack:
        enabled: true
        channel: "#maintenance"
        mentions: ["@engineering-team"]

      email:
        enabled: false
        to: [devops@example.com]

      github:
        enabled: true
        create_issue: false # Create tracking issue
        create_discussion: true # Create discussion post

    # Notification templates
    templates:
      before:
        title: "🔧 Scheduled Maintenance: {{ task_type }}"
        message: |
          Scheduled maintenance will begin in {{ minutes }} minutes.

          **Type:** {{ task_type }}
          **Start:** {{ start_time }}
          **Duration:** {{ duration }} minutes
          **Impact:** {{ impact_level }}

          **Tasks:**
          {{ tasks }}

          **Reasoning:** {{ reasoning }}

      after:
        title: "✅ Maintenance Complete: {{ task_type }}"
        message: |
          Scheduled maintenance has completed successfully.

          **Type:** {{ task_type }}
          **Duration:** {{ actual_duration }} minutes
          **Tasks Completed:** {{ completed_tasks }}

          **Results:**
          {{ results }}

# Machine Learning Configuration
ml_config:
  # Enable ML-based prediction
  enabled: true

  # Historical data lookback (days)
  lookback_days: 28

  # Minimum data points required for ML prediction
  min_data_points: 50

  # Confidence threshold for ML predictions
  min_confidence: 0.6

  # Fallback to fixed schedule if confidence too low
  fallback_to_fixed: true

  # Feature weights for impact calculation
  feature_weights:
    commit_activity: 0.3
    workflow_activity: 0.4
    issue_activity: 0.2
    pr_activity: 0.1

  # Model configuration
  model:
    type: time_series # Options: time_series, pattern_matching
    update_frequency: weekly

# Risk Management
risk_management:
  # Risk assessment for tasks
  risk_levels:
    dependency_update:
      security: low # Security updates are well-tested
      major: high # Major version changes
      minor: medium
      patch: low

    cleanup:
      branches: low
      artifacts: low
      cache: medium

    optimization:
      database: high
      cache: medium
      performance: low

  # Actions based on risk level
  risk_actions:
    low:
      auto_execute: true
      require_approval: false
      backup_before: false

    medium:
      auto_execute: false
      require_approval: true
      backup_before: true

    high:
      auto_execute: false
      require_approval: true
      backup_before: true
      notify_oncall: true

# Rollback Configuration
rollback:
  enabled: true

  # Automatic rollback triggers
  triggers:
    - health_check_fail
    - error_rate_increase
    - response_time_increase

  # Health check configuration
  health_checks:
    enabled: true
    interval_seconds: 60
    failure_threshold: 3

  # Rollback window (how long to monitor after maintenance)
  monitoring_window_minutes: 30

# Audit and Compliance
audit:
  enabled: true
  retention_days: 365

  # Fields to log
  fields:
    - timestamp
    - task_type
    - scheduled_time
    - actual_start
    - actual_end
    - duration
    - impact_score
    - success
    - tasks_completed
    - tasks_failed
    - rollback_triggered

  # Export configuration
  export:
    enabled: true
    format: json
    destination: .github/audit/maintenance/

# Task-Specific Configuration
tasks:
  dependency_update:
    max_concurrent: 5 # Max PRs to merge at once
    test_timeout_minutes: 30
    required_checks:
      - test
      - lint
      - security-scan

  cleanup:
    batch_size: 10 # Process N items at a time
    dry_run_first: true # Always do dry run first

  optimization:
    backup_before: true
    verify_after: true
