# Week 9 Validation Configuration
# Comprehensive testing and monitoring for all advanced automation capabilities

# Validation Settings
validation:
  # Enable validation framework
  enabled: true

  # Validation schedule
  schedule:
    # Run validations automatically
    auto_run: true
    # Cron schedule: Daily at 2 AM
    cron: "0 2 * * *"
    # Validation interval (hours)
    interval_hours: 24

  # Notification channels for validation results
  notifications:
    on_failure: true
    on_success: false # Only notify failures by default
    channels:
      - type: "slack"
        channel: "#automation-validation"
      - type: "email"
        recipients: ["automation-team@example.com"]

# Capability-Specific Validation Settings
capabilities:
  auto-merge:
    # Test auto-merge eligibility checker
    enabled: true
    test_pr_count: 20
    min_merge_rate: 0.30 # At least 30% merge rate expected
    alert_threshold: 0.20 # Alert if below 20%

  intelligent-routing:
    # Test intelligent routing algorithm
    enabled: true
    test_pr_count: 50
    min_assignment_rate: 0.80 # At least 80% PRs should get reviewers
    workload_balance_threshold: 0.10 # Max 10% variance

  self-healing:
    # Test self-healing workflow
    enabled: true
    test_run_count: 50
    min_recovery_rate: 0.70 # At least 70% recovery expected
    max_failure_rate: 0.30 # Alert if >30% failures

  maintenance:
    # Test proactive maintenance
    enabled: true
    check_scheduled_tasks: true
    check_completion_rate: true
    min_completion_rate: 0.90 # 90% tasks should complete

  analytics:
    # Test enhanced analytics ML
    enabled: true
    check_model_files: true
    required_models: 3 # Random Forest, Gradient Boosting, Neural Network
    min_accuracy: 0.85 # 85% accuracy target
    alert_accuracy: 0.80 # Alert if below 80%

  sla-monitoring:
    # Test SLA monitoring
    enabled: true
    test_item_count: 50
    min_compliance_rate: 0.95 # 95% SLA compliance
    check_breach_detection: true

  incident-response:
    # Test incident response automation
    enabled: true
    check_configuration: true
    check_runbooks: true
    check_incident_records: true

# Metrics Collection
metrics:
  # Enable metrics collection during validation
  enabled: true

  # Metrics to collect
  tracked_metrics:
    - auto_merge_eligibility_rate
    - auto_merge_success_rate
    - routing_assignment_rate
    - routing_review_time
    - self_healing_recovery_rate
    - maintenance_completion_rate
    - analytics_prediction_accuracy
    - sla_compliance_rate
    - incident_detection_time
    - incident_mttr

  # Export metrics to Prometheus
  export:
    enabled: true
    format: "prometheus"
    endpoint: "/metrics/validation"

# Reporting
reporting:
  # Generate validation reports
  enabled: true

  # Report schedule
  schedules:
    daily:
      enabled: true
      time: "08:00"
      recipients: ["automation-team@example.com"]

    weekly:
      enabled: true
      day: "Monday"
      time: "09:00"
      recipients: ["automation-team@example.com", "management@example.com"]

    monthly:
      enabled: true
      day: 1
      time: "10:00"
      recipients: ["all"]

  # Report formats
  formats:
    - json
    - markdown
    - html

  # Report content
  include:
    - validation_summary
    - capability_status
    - metrics_trends
    - issues_and_warnings
    - recommendations

# Thresholds and Alerts
thresholds:
  # Overall validation success
  min_passed_capabilities: 6 # At least 6/7 must pass
  max_warnings: 5 # Alert if more than 5 warnings

  # Capability-specific thresholds
  critical_capabilities:
    # These must always pass
    - sla-monitoring
    - incident-response
    - self-healing

  # Degradation alerts
  degradation:
    enabled: true
    # Alert if performance drops more than this percentage
    threshold_percentage: 10
    # Compare against this many previous validations
    lookback_count: 7

# Remediation
remediation:
  # Automatic remediation actions
  enabled: true

  # Actions to take on validation failures
  actions:
    configuration_missing:
      - create_default_config
      - notify_team

    low_accuracy:
      - retrain_model
      - notify_team

    sla_breach:
      - investigate_cause
      - create_incident

    repeated_failures:
      - escalate_to_management
      - create_critical_incident

# Advanced Options
advanced:
  # Parallel validation execution
  parallel_execution:
    enabled: true
    max_concurrent: 3

  # Validation data retention
  retention:
    days: 90
    export_before_delete: true
    export_format: "json"

  # Integration testing
  integration_tests:
    enabled: true
    # Test cross-system interactions
    test_analytics_routing: true
    test_sla_incidents: true
    test_self_healing_incidents: true

  # Performance testing
  performance_tests:
    enabled: false
    load_test_duration_minutes: 10
    max_response_time_ms: 1000
