name: CI Pipeline

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: '{{ORG_NAME}}/.github/.github/workflows/reusable/ci-pipeline.yml@main'
    with:
      language: both
      python-versions: '["3.12"]'
      node-versions: '["20"]'
