name: Dependency Updates

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # Check for dependency updates weekly
    - cron: 0 0 * * 1

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js (if applicable)
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Update npm dependencies
        if: hashFiles('package.json') != ''
        run: |
          npm update
          npm audit fix

      - name: Set up Python (if applicable)
        if: hashFiles('requirements.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Update Python dependencies
        if: hashFiles('requirements.txt') != ''
        run: |
          pip install --upgrade pip
          pip list --outdated

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: automated dependency updates"
          body: |
            Automated dependency updates

            This PR includes:
            - Updated npm packages (if applicable)
            - Updated Python packages (if applicable)
            - Security fixes

            Please review the changes before merging.
          branch: automated-dependency-updates
          delete-branch: true
          labels: dependencies,automated
