name: Standard Python Setup
description: Standardized Python setup with repository variable support and sensible defaults

inputs:
  python-version:
    description: Python version to use. Falls back to vars.PYTHON_VERSION_DEFAULT, then '3.12'
    required: false
    default: ''
  cache:
    description: Whether to cache pip dependencies
    required: false
    default: 'true'
  cache-dependency-path:
    description: Path to requirements file(s) for cache key
    required: false
    default: '**/requirements*.txt'

outputs:
  python-version:
    description: The Python version that was set up
    value: ${{ steps.setup.outputs.python-version }}
  cache-hit:
    description: Whether the cache was hit
    value: ${{ steps.setup.outputs.cache-hit }}

runs:
  using: composite
  steps:
  - name: Determine Python version
    id: version
    shell: bash
    run: |
      # Priority: input > repository variable > default
      INPUT_VERSION="${{ inputs.python-version }}"
      REPO_VAR_VERSION="${{ vars.PYTHON_VERSION_DEFAULT }}"
      DEFAULT_VERSION="3.12"

      if [ -n "$INPUT_VERSION" ]; then
        VERSION="$INPUT_VERSION"
        echo "Using input version: $VERSION"
      elif [ -n "$REPO_VAR_VERSION" ]; then
        VERSION="$REPO_VAR_VERSION"
        echo "Using repository variable PYTHON_VERSION_DEFAULT: $VERSION"
      else
        VERSION="$DEFAULT_VERSION"
        echo "Using default version: $VERSION"
      fi

      echo "version=$VERSION" >> $GITHUB_OUTPUT

  - name: Set up Python ${{ steps.version.outputs.version }}
    id: setup
    uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b    # ratchet:actions/setup-python@v5
    with:
      python-version: ${{ steps.version.outputs.version }}
      cache: ${{ inputs.cache == 'true' && 'pip' || '' }}
      cache-dependency-path: ${{ inputs.cache-dependency-path }}

  - name: Upgrade pip
    shell: bash
    run: python -m pip install --upgrade pip
