name: 🔒 Security Vulnerability
description: Report a security vulnerability (please use private security advisory for sensitive issues)
title: "[Security] "
labels: [security, high-priority]
assignees:
  - ivi374forivi
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Notice

        **For sensitive security vulnerabilities, please DO NOT create a public issue.**
        Instead, please report them privately through our [Security Advisory](https://github.com/ivi374forivi/.github/security/advisories/new) page.

        This template is for security issues that are:
        - Already publicly disclosed
        - Low severity issues that don't pose immediate risk
        - Security enhancements or hardening suggestions

        Thank you for helping keep our projects secure!

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low (Security enhancement, minor issue)
        - Medium (Moderate risk, requires authentication)
        - High (Significant risk, affects multiple users)
        - Critical (Immediate risk, RCE, data breach, etc.)
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Cross-Site Scripting (XSS)
        - SQL Injection
        - Cross-Site Request Forgery (CSRF)
        - Insecure Dependencies
        - Exposed Secrets/Credentials
        - Information Disclosure
        - Denial of Service (DoS)
        - Cryptographic Issue
        - Input Validation
        - Security Misconfiguration
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the security issue
      placeholder: Describe the security vulnerability, its impact, and potential consequences
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Execute '...'
        4. Observe security issue
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Who is affected?
        - What data/systems are at risk?
        - What can an attacker do?
        - What is the likelihood of exploitation?
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept (if applicable)
      description: Provide a PoC if you have one (please be responsible)
      placeholder: |
        Include code, screenshots, or demonstrations
        DO NOT include actual exploits that could be used maliciously
      render: shell

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this vulnerability?
      placeholder: |
        - Version 1.0.0
        - Version 2.0.0
        - All versions

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this issue?
      placeholder: Describe potential fixes or mitigations

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details where vulnerability was discovered
      placeholder: |
        - OS: [e.g., Ubuntu 22.04]
        - Browser: [e.g., Chrome 120]
        - Version: [e.g., 1.0.0]
        - Configuration: [any relevant settings]

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant security advisories, CVEs, or documentation
      placeholder: |
        - CVE-XXXX-XXXXX
        - https://...
        - Related security advisories

  - type: checkboxes
    id: checklist
    attributes:
      label: Security Checklist
      description: Please confirm the following
      options:
        - label: I have verified this is a genuine security issue
          required: true
        - label: I have not disclosed this vulnerability publicly elsewhere
          required: true
        - label: I understand that sensitive security issues should be reported privately
          required: true
        - label: I have provided enough information to reproduce the issue
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ivi374forivi/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
