name: 📋 Task
description: Create a task or work item
title: '[Task] '
labels: [task]
assignees:
- 
body:
- type: markdown
  attributes:
    value: |
      Use this template to create a task or work item for the project.

- type: textarea
  id: description
  attributes:
    label: Description
    description: Provide a clear description of the task
    placeholder: Describe what needs to be done and why
  validations:
    required: true

- type: textarea
  id: acceptance-criteria
  attributes:
    label: Acceptance Criteria
    description: Define the criteria that must be met for this task to be considered complete
    placeholder: |
      - [ ] Criterion 1
      - [ ] Criterion 2
      - [ ] Criterion 3
  validations:
    required: true

- type: dropdown
  id: priority
  attributes:
    label: Priority
    description: What is the priority of this task?
    options:
    - Low
    - Medium
    - High
    - Critical
  validations:
    required: false

- type: textarea
  id: dependencies
  attributes:
    label: Dependencies (Optional)
    description: List any dependencies or blockers for this task
    placeholder: |
      - Depends on #123
      - Blocked by #456
      - Requires approval from...
  validations:
    required: false

- type: input
  id: due-date
  attributes:
    label: Due Date (Optional)
    description: When should this task be completed?
    placeholder: YYYY-MM-DD
  validations:
    required: false

- type: dropdown
  id: complexity
  attributes:
    label: Estimated Complexity
    description: How complex is this task?
    options:
    - Small (< 1 day)
    - Medium (1-3 days)
    - Large (> 3 days)
    - Unknown
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: Add any other relevant information about this task
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our Code of Conduct
    options:
    - label: I agree to follow this project's Code of Conduct
      required: true
