#!/bin/bash
# Quick reference for GitHub Projects management

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          GitHub Projects Quick Reference                     ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 VIEW PROJECTS"
echo "  Browser:  https://github.com/orgs/ivviiviivvi/projects"
echo "  CLI:      gh project list --owner ivviiviivvi"
echo ""
echo "➕ ADD ITEMS TO PROJECTS"
echo "  All items:     python3 add-items-to-projects.py --org ivviiviivvi --repo .github"
echo "  Issues only:   python3 add-items-to-projects.py --org ivviiviivvi --repo .github --issues-only"
echo "  PRs only:      python3 add-items-to-projects.py --org ivviiviivvi --repo .github --prs-only"
echo "  Dry run:       python3 add-items-to-projects.py --org ivviiviivvi --repo .github --dry-run"
echo ""
echo "🔧 CONFIGURE AUTOMATION"
echo "  Interactive:   ./complete-project-setup.sh"
echo "  Read guide:    cat setup-automation-rules.md"
echo "  Project #8:    https://github.com/orgs/ivviiviivvi/projects/8/workflows"
echo ""
echo "📚 DOCUMENTATION"
echo "  Complete:      cat ../GITHUB_PROJECTS_SETUP_COMPLETE.md"
echo "  Automation:    cat setup-automation-rules.md"
echo "  Scripts:       cat README_PROJECTS.md"
echo ""
echo "🔑 TOKEN MANAGEMENT"
echo "  From 1Pass:    export GH_TOKEN=\$(op read \"op://Personal/master-org-token-011726/password\")"
echo "  Verify:        echo \"\${GH_TOKEN:0:10}...\""
echo ""
echo "📈 PROJECT STATISTICS"
echo "  Project #8:    gh api graphql -f query='{organization(login:\"ivviiviivvi\"){projectV2(number:8){items{totalCount}}}}'"
echo "  All projects:  for i in {8..14}; do gh api graphql -f query='{organization(login:\"ivviiviivvi\"){projectV2(number:'\$i'){title items{totalCount}}}}'; done"
echo ""
echo "🎯 NEXT STEPS"
echo "  1. Configure automation rules (setup-automation-rules.md)"
echo "  2. Create views for each project (6 views per project)"
echo "  3. Train team on project usage"
echo ""
